name: Build Artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push
        uses: alexthemaster/action-build-typescript@v1.3.1

      - name: Save bundle artifact
        uses: actions/upload-artifact@v4
        with:
          path: .
          if-no-files-found: error
          retention-days: 14
